# Generated by Django 5.1.2 on 2025-03-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
