# Generated by Django 5.1.2 on 2025-03-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0002_alter_businesshours_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
