# Generated by Django 5.1.2 on 2025-03-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0004_alter_service_options_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('barber', 'date', 'start_time')},
        ),
    ]
