# Generated by Django 5.1.2 on 2025-03-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0005_appointment_amount_appointment_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
